- .gitignore
- README.md
- app/src/androidTest/java/com/facebook/encapp/CodecValidationInstrumentedTest.java
- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/Transcoder.java
- scripts/offline_transcode.sh
- setup.sh
Includes:
* more fixes in `.gitignore`
* added more information to `README.md` on how to run a minimal encoding
experiments
* linted `scripts/offline_transcode.sh`
* removed stale references in `setup.h`
> encapp: add minimal encoder example

- scripts/encapp_tests.py
- scripts/plot_frame_scores.py
- scripts/plot_rd.py
Update encapp_test.py  to support YUV
> Python script

- app/src/main/java/com/facebook/encapp/MainActivity.java
- scripts/encapp_search.py
- scripts/encapp_tests.py
Added a error check for faulty combinations in the test script
Added a search/indexer for the json files
> Fixed concurrent limit to be obeyed

- scripts/encapp.py
- scripts/plot_encapp_stats.py
Includes:
* make linter happy
* move argparse description to docstring
> encapp: scripts: minor changes

- tests-human/Makefile
- tests-human/bitrates.json
- tests-human/dynamic_bitrate.json
- tests-human/dynamic_framedrop.json
- tests-human/dynamic_framerate.json
- tests-human/dynamic_idr.json
- tests-human/extraconfig.json
- tests-human/idr.json
- tests-human/ltr-2ref.json
- tests-human/ltr-4ref.json
- tests-human/simple.json
- tests-human/tl2.json
- tests-java/Makefile
- tests-java/bitrates.json
- tests-java/dynamic_bitrate.json
- tests-java/dynamic_framedrop.json
- tests-java/dynamic_framerate.json
- tests-java/dynamic_idr.json
- tests-java/extraconfig.json
- tests-java/idr.json
- tests-java/ltr-2ref.json
- tests-java/ltr-4ref.json
- tests-java/simple.json
- tests-java/tl2.json
Proposal for converting all the current tests.
> encappng: add human and java JSON configuration files

- scripts/encapp_quality.py
* changed log format to json so the plot script can read it easily
* plot per frame is updated and reads the log output from ffmpeg
> encapp: Update to vmaf plotting and handling

- app/src/main/java/com/facebook/encapp/Encoder.java
- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/utils/CameraSource.java
- app/src/main/java/com/facebook/encapp/utils/MediaCodecInfoHelper.java
- app/src/main/java/com/facebook/encapp/utils/SystemLoad.java
Reorganize imports from encapp app using android studio tools.
> encapp: lint, optimize imports at android app.

- README.md
Fixed codeblock format at README.md
> encapp: fix readme format.

- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/utils/SizeUtils.java
> encapp: make linter happier

- scripts/encapp.py
- scripts/encapp_tool/adb_cmds.py
- scripts/encapp_tool/app_utils.py
- scripts/tests/unit/adb_cmds_test.py
- scripts/tests/unit/app_utils_test.py
Moved encapp install functionality to encapp_tool package with
corresponding unit test
> encapp: move encapp install functionality to encapp_tool

- scripts/tests/system/test_encapp.py
Add system test for encapp.py uninstall
and list commands
> encapp: add uninstall and list tests

- scripts/tests/system/test_encapp_verify.py
Add system test for encapp_verify.py -h
> encapp: add system test for verify

- app/src/main/java/com/facebook/encapp/Encoder.java
- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/SurfaceEncoder.java
- app/src/main/java/com/facebook/encapp/SurfaceTranscoder.java
- app/src/main/java/com/facebook/encapp/utils/OutputMultiplier.java
- app/src/main/java/com/facebook/encapp/utils/VsyncHandler.java
- app/src/main/java/com/facebook/encapp/utils/VsyncListener.java
Instead of a sleep the wait will be controlled by callbacks from vsync, possibly
minimizing the likelyhood of variation by high load.
> encapp: Realtime timing now in relation to vsync

- README.md
> encapp: Added examples and info about camera and decoder

- app/src/main/java/com/facebook/encapp/Encoder.java
Contribution from Ittiam Systems Pvt. Ltd.
> Fix sleep logic in realtime mode

- app/src/main/java/com/facebook/encapp/MainActivity.java
* Encapp would hang for configureation errors since the main loop would wait for init to be complete. This is now corrected,
* UI log message will now appear in logcat
> encapp: Fix for exiting failed test

- scripts/encapp.py
> encapp: Add placeholder fro decode functionlity

- app/src/main/java/com/facebook/encapp/BufferEncoder.java
- app/src/main/java/com/facebook/encapp/Encoder.java
Contribution from Ittiam Systems Pvt. Ltd.
> encapp: Fix missing last frame in the BufferEncoder

- app/src/main/java/com/facebook/encapp/BufferDecoder.java
- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/utils/Statistics.java
- tests/bitrate_buffer_decoder.pbtxt
Contribution from Ittiam Systems Pvt. Ltd.
> encapp: Add support for buffer decoder

- app/src/main/java/com/facebook/encapp/utils/Statistics.java
Now clean and buildable on lower api versions.
> encapp: Forgot to remove systrace entries

- app/src/main/java/com/facebook/encapp/BufferDecoder.java
Contribution from Ittiam Systems Pvt. Ltd.
> encapp: Fix for frame processing time measurement in buffer decoder

- README.md
- app/src/main/java/com/facebook/encapp/BufferDecoder.java
- app/src/main/java/com/facebook/encapp/Encoder.java
- app/src/main/java/com/facebook/encapp/SurfaceTranscoder.java
- app/src/main/java/com/facebook/encapp/utils/Statistics.java
- app/src/main/java/com/facebook/encapp/utils/TestDefinitionHelper.java
- scripts/encapp.py
- scripts/encapp_plot.py
- scripts/encapp_quality.py
- scripts/encapp_search.py
- scripts/encapp_stats_to_csv.py
- scripts/encapp_tool/adb_cmds.py
- scripts/encapp_tool/app_utils.py
- scripts/encapp_tool/ffutils.py
- scripts/encapp_verify.py
Added host support for running Encapp on ios devices using idb (https://github.com/facebook/idb).
The xcode project may be pushed later.
Merge upstream and verified tests in README.md.
> encapp: Ios support added (only for the python part)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/facebook/encapp/MainActivity.java
- app/src/main/java/com/facebook/encapp/utils/MediaCodecInfoHelper.java
* new target sdk level 31
* added vendor specific parameters for codecs
> encapp: update target sdk level to 31 and list parameters extended

- scripts/encapp.py
- scripts/encapp_corpus_test.py
- scripts/encapp_quality.py
* run all files in a directory with option filters for framerate and resolution.
* quality will calculated automatically and saved in csv file
> enapp: add a "corpus" quality test

- scripts/encapp.py
- scripts/encapp_search.py
- scripts/vmaf_json2csv.py
```
$ /usr/bin/black scripts/*py
```
> encapp: make linter happy

- scripts/plot_quality_metric_stats.py
Added two new options
--diff diffs metric value between different data sources, trying to
match bitrate and source
--split_on_datasources plots data sources as separate entities rather
than mergin them.
Note: not all combinatins will make sense but a typical way of using these options is to run encapp with two sets of results with tweaks to a common setting and do:
"
>python3 plot_quality_metric_stats.py SET1 SET2 \
--split_by source --diff --split_on_datasource -m psnr
"
Which will plot the difference in psnr with all sources on separate graphs with the hue connected to SETX.
Removing "--split_by source" will have everything in one graph and (probably) hard to read.
> encapp: plot quality metrics updated

- scripts/encapp_quality.py
The environment variable VMAF_MODEL_PATH still overrrides and can be used to use a custom model.
> encapp: removed the forced path to vmaf and added choices as cli args

- scripts/encapp.py
Same as bitrate expansion for cli.
I.e.
configure {
codec: "OMX.google.h264.encoder"
bitrate: "200k-400k-100k"
resolution: "176x144,1280x720"
}
Which will result in six files run.
Expansion is START-STOP-STEP.
Multiple ranges or single values are comma separated.
> encapp: enable expand for protobuf variables
