- scripts/encapp.py
- scripts/encapp_search.py
- scripts/encapp_verify.py
There's one hard issue to fix:
```
$ flake8 scripts/*py
scripts/encapp.py:66:19: P204: Could not statically determine the binary parameter. Please make sure your command is properly escaped. If you're using `eval`, please don't (ever!). If you're shelling out to a process, please pass in an array of arguments. If you do need shell support, make sure you're escaping all the arguments (e.g. with `shlex.quote`).
scripts/encapp.py:81:19: P204: Could not statically determine the binary parameter. Please make sure your command is properly escaped. If you're using `eval`, please don't (ever!). If you're shelling out to a process, please pass in an array of arguments. If you do need shell support, make sure you're escaping all the arguments (e.g. with `shlex.quote`). …
```
> encapp: make linter happy

- tests/Makefile
This will avoid files being completely removed when their
syntax is broken.
> encapp: avoid clobbering json files on syntax issues

- tests-human/tests.proto
Includes:
* use enum ("`ValueType`") for types instead of string
* use float for framerates (except the configure frame_rate,
which android defines as an int)
* use int for `playout_frames`
> encapp: minor changes on protobuf definition

- scripts/encapp.py
Tested:
```
$ ./scripts/encapp.py list
Traceback (most recent call last):
File "/home/chemag/proj/encapp/./scripts/encapp.py", line 690, in <module>
main(sys.argv)
File "/home/chemag/proj/encapp/./scripts/encapp.py", line 665, in main
assert install_ok(serial, options.debug), (
AssertionError: Apps not installed in ...
```
> encapp: have script report uninstalled apps

- README.dev.md
Fixed markdown format at section 3 and typos
at README.dev.md
> Readme dev fixed typos and formatting

- scripts/encapp.py
- scripts/encapp_quality.py
- scripts/encapp_tool/adb_cmds.py
- scripts/encapp_verify.py
- scripts/tests/adb_cmds_unittest.py
Migrate functions from encapp.py scripts
to encapp_tool.adb_cmds package, added documentation
and unit test for those functions.
Signed-off-by: Hideki Mendoza <hidekim@fb.com>
> encapp: move adb commands to encapp_tool package

- app/src/main/java/com/facebook/encapp/MainActivity.java
- scripts/encapp.py
Set encapp app version to 1.5, and use display toast
if unable to start activity to grant all file access permission.
On encapp.py scripts,request encapp permission programatically
as part of installation and force-stop the app after install.
> encapp: grant encapp permissions and display toast if missing

- scripts/encapp_quality.py
- scripts/encapp_search.py
- scripts/encapp_stats_to_csv.py
- scripts/encapp_verify.py
- scripts/plot_frame_scores.py
- scripts/plot_rd.py
Lint python files to conform to the PEP8 style guide
```
$ autopep8 --version
autopep8 1.6.0 (pycodestyle: 2.8.0)
$ autopep8 --in-place --aggresive scripts/*py
```
> encapp: lint: Run autopep8 on all python files

- .github/workflows/build.yml
- .github/workflows/tests.yml
- scripts/tests/test_adb_cmds_unittest.py
I'm proposing to start using some continuous integration tool. Github workflows are already integrated in github so no 3rd party service is required.
Added two jobs with some basic tests:
build: https://github.com/michalkielan/encapp/actions/runs/2444651913
test: https://github.com/michalkielan/encapp/actions/runs/2444651914
The job includes:
- Python lint:
- `pylint` - Temporary return 0 always because of some minor failures: not used modules, not used variables etc.
- `flake8` - The build will fail if there are some python syntax errors or undefined names.
- Pytest:
- Run `pytest` - the unit tests filename was changed, must start with `test*` otherwise the file is not recognizable as a test.
- Android:
- Build apk
- Run `encapp.py`: `install` and `list` on android emulator
> encapp: Enable continuous integration builds

- .github/workflows/build.yml
Builds sometimes are failing on adb emulator, leave the ./gradle build and kill the adb tests for investigation
> encapp: ci: remove adb emulator tests

- .github/workflows/tests.yml
- scripts/tests/system/test_encapp.py
- scripts/tests/unit/__init__.py
- scripts/tests/unit/adb_cmds_test.py
Add system test for encapp.py script intending to use real
android device connected to the host machine.
Split scripts/tests directory into system and unit tests
Unit tests intended to be run with pytest or unittest
System tests intended to be run with pytest
$ ANDROID_SERIAL=<serial_no> python3 -m pytest tests/system/test_encapp.py
> encapp: add system test for encapp.py script

- scripts/encapp.py
- scripts/encapp_tool/adb_cmds.py
- scripts/encapp_tool/app_utils.py
- scripts/tests/unit/adb_cmds_test.py
- scripts/tests/unit/app_utils_test.py
Moved install_ok and unistall function from encapp.py to
encapp_tool package.
Added unit test and docstring
> encapp: refactor encapp.py by moving install functions

- scripts/encapp.py
Fixed paths and commands executed by
encapp.py to run on windows machines
Tested by running:
python encapp.py run ../tests/camera_parallel.pbtxt
> encapp: fix encapp.py run for windows support

- tests/b_frames.pbtxt
From https://developer.android.com/reference/android/media/MediaFormat#KEY_MAX_B_FRAMES
> encapp: tests: add a tests that uses B-frames

- tests/b_frames.pbtxt
In our case, B-frame requires VBR mode.
Tested:
```
$ ffmpeg -i akiyo_qcif.y4m -f rawvideo -pix_fmt nv12 /tmp/akiyo_qcif.yuv
$ tate01 ./scripts/encapp.py run tests/b_frames.pbtxt
...
adb -s 2C21BRCC6J00T2 shell ls /sdcard/
pull encapp_377e4c44-e0b4-4383-bab4-78cc0a76f894.json to testing_PortalGo_2022-09-13_18_48/b_frames_files
pull encapp_377e4c44-e0b4-4383-bab4-78cc0a76f894.mp4 to testing_PortalGo_2022-09-13_18_48/b_frames_files
results collect: ['testing_PortalGo_2022-09-13_18_48/b_frames_files/encapp_377e4c44-e0b4-4383-bab4-78cc0a76f894.json']
```
And then:
```
$ ffmpeg -i testing_PortalGo_2022-09-13_18_48/b_frames_files/encapp_377e4c44-e0b4-4383-bab4-78cc0a76f894.mp4 -vcodec copy /tmp/foo.264
...
$ h264nal --noas-one-line /tmp/foo.264  -  |grep slice_type
slice_type: 2
slice_type: 0 …
```
> encapp: fix B-frame test

- scripts/encapp.py
- scripts/encapp_tool/adb_cmds.py
The encapp.py script will before running a test case try to reset logcat and after the test capture current log looking for failure prints. If failed test is found logcat is written to output folder.
> encapp: Added test failed detection

- scripts/encapp.py
Tested:
```
$ ./scripts/encapp.py -ddd list --device-workdir /data/data/com.facebook.encapp
adb devices -l
...
adb -s ... pull /data/data/com.facebook.encapp/codecs.txt codecs_model.txt
encoders {
MediaCodec {
name: c2.qti.avc.encoder
canonical_name: c2.qti.avc.encoder
is_alias: false
is_encoder: true
is_hardware_accelerated: true
is_software_only: false
is_vendor: true
...
```
> encapp: fix encapp list command

- scripts/encapp.py
* running a single test without replacement of parameters is fixed
* running -r for bitrate replacement is fixed
> encapp: Fix for broken singel test and range test

- scripts/encapp.py
Added a couple of options that require conversion to int/float before assignment.
Tested:
```
$ export ENCODER=OMX.qcom.video.encoder.avc
$ export BITRATE=5Mbps
$ ~/proj/encapp/scripts/encapp.py -ddd run ~/proj/encapp/tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -e input.pix_fmt nv12 -i /tmp/out.y4m --codec ${ENCODER} --bitrate ${BITRATE} --local-workdir /tmp/testing --ignore-results --fast-copy -e input.stoptime_sec 20
...
```
> encapp: script: fix on int/float CLI options

- scripts/encapp.py
Tested:
Before:
```
$ ./scripts/encapp.py -ddd run ./tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -e input.pix_fmt nv12 -i /tmp/out.nv12.yuv --codec c2.android.avc.encoder --bitrate 5Mbps --local-workdir /tmp/testadb devices -l
...
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
new_value = type_checker.CheckValue(new_value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/google/protobuf/internal/type_checkers.py", line 178, in CheckValue
raise TypeError(message)
TypeError: 'nv12' has type <class 'str'>, but expected one of: (<class 'int'>,)
...
```
After:
```
$ ~/proj/encapp/scripts/encapp.py -ddd run …
```
> encapp: scripts: support for enums in CLI options

- app/build.gradle
- app/src/main/java/com/facebook/encapp/utils/Statistics.java
- ios/Encapp/tests.pb.swift
- ios/Encapp/utils/Statistics.swift
- proto/tests.proto
- scripts/encapp.py
- scripts/encapp_corpus_test.py
- scripts/proto/tests_pb2.py
Added common.output_filename
Placeholder markers are []
e.g. [common.id].[input.resolution].[configuration.bitrate]-[XXXX] X is a substitution marker for A random hex number (1-f) If not set the filename will be encapp_uuid
> encapp: added output filename to common and updated version to 1.17

- scripts/encapp.py
\/ is not a valid escape sequence, if that's supposed to be a literal \ we can use a raw string (or \\)
> fix \/ is not a valid escape sequence

- app/build.gradle
which is minimum version with macOS aarch64 builds
> upgrade protobuf compiler to 3.18 

- scripts/encapp.py
Replace use of protoc.
This removes an extra dependency, and unifies text protobuf code.
> encapp: use python to check text protobuf
